services:
  docker-mysql:
    image: mysql:9.5
    environment:
      - MY_SQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MY_SQL_PASSWORD=${DB_PASSWORD}
      - MY_SQL_DATABASE=database
      - MY_SQL_USERNAME=${DB_USERNAME}
    ports:
      - 3307:3006
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - docker-mysql
    networks:
      - buzy_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:80
    depends_on:
      - backend
    networks:
      - buzy_network

networks:
  buzy_network:
    driver: bridge
